# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install -c anaconda numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
np.array(my_list) # cast list as an array

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [ ]:
# Matrix (2D array) - cast a list of lists

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mat = np.array(my_mat)

In [10]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

Built-in methods are faster

### arange

Return evenly spaced values within a given interval.

In [13]:
np.arange(0,11,2) #(start, stop, step) link python range()

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5)) # tuple of matrix dimensions

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [23]:
# don't confuse linspace for range
np.linspace(0,1,20) #(start,stop,number of points)
# returns 1D array (vector)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## eye

Creates an identity matrix

In [26]:
np.eye(7) # usefule for linea algebra problems, 2D square matrix with diagonal of 1's

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [28]:
np.random.rand(5)

array([0.57679973, 0.93699932, 0.18222212, 0.68619311, 0.64772213])

In [30]:
np.random.rand()

0.46499153872193044

In [33]:
np.random.rand(3,5) # no need of tuple

array([[0.56273041, 0.52336692, 0.17045972, 0.18644822, 0.69838255],
       [0.41831168, 0.42168254, 0.02425064, 0.01377941, 0.97077608],
       [0.91427555, 0.01897453, 0.71791491, 0.81265657, 0.94335567]])

### randn

Return a sample (or samples) from the Gaussian "standard normal" distribution. Unlike rand which is uniform:

In [34]:
np.random.randn(2)

array([0.63985853, 1.31488078])

In [35]:
np.random.randn(2,2)

array([[ 0.63797118, -0.96910871],
       [-0.68785613,  1.61078344]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [37]:
np.random.randint(0,101) # (low inclusive, high exclusive)

75

In [39]:
np.random.randint(0,101, 10) # (low inclusive, high exclusive, size)

array([ 6, 85, 81, 75, 31,  2, 60, 86, 68, 73])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
randarr = np.random.randint(0,50,10)

In [43]:
randarr

array([35, 26, 31, 36, 35,  3, 45, 23, 43, 11])

## Reshape
Returns an array containing the same data with a new shape.

In [46]:
arr.reshape(5,5) #(rows, cols) # number elements must be same as in original array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
randarr.reshape(2,5)

array([[35, 26, 31, 36, 35],
       [ 3, 45, 23, 43, 11]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [49]:
randarr

array([35, 26, 31, 36, 35,  3, 45, 23, 43, 11])

In [50]:
randarr.max()

45

In [51]:
randarr.min()

3

In [53]:
randarr.argmax() # index of max

6

In [54]:
randarr.argmin() # index of min

5

## Shape

Shape is an attribute that arrays have (not a method):

In [57]:
arr.shape

(25,)

In [59]:
randarr.shape

(10,)

In [60]:
arr.reshape(5,5).shape

(5, 5)

In [61]:
arr2 = arr.reshape(5,5)

In [62]:
arr2.shape

(5, 5)

In [63]:
arr3 = arr.reshape(25,1) #2D

In [64]:
arr3.shape

(25, 1)

In [66]:
arr4 = arr.reshape(1,25) #2D

In [67]:
arr4.shape

(1, 25)

In [68]:
arr3

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [69]:
arr4 #2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [70]:
arr #1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### dtype

You can also grab the data type of the object in the array:

In [75]:
arr.dtype # 32bit integer data type

dtype('int32')

In [76]:
arr4.dtype

dtype('int32')

In [77]:
arr3.dtype

dtype('int32')

In [78]:
randarr.dtype

dtype('int32')

In [79]:
from numpy.random import randint

In [81]:
randint(2,10,50)

array([3, 9, 9, 9, 6, 3, 2, 5, 7, 5, 8, 4, 7, 4, 9, 6, 4, 5, 9, 9, 7, 5,
       4, 5, 4, 3, 5, 2, 3, 4, 5, 4, 8, 5, 8, 3, 5, 3, 6, 3, 6, 5, 2, 6,
       7, 5, 3, 4, 9, 8])