# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [4]:
# sample array
arr = np.arange(0,11) # 11 elements, 0 to 10

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [9]:
arr[8]

8

In [10]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [12]:
arr[1:5]

array([1, 2, 3, 4])

In [13]:
arr[:5]

array([0, 1, 2, 3, 4])

In [14]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [15]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
arr[:]

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [16]:
arr[0:5] = 100

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_arr = arr[0:6]

In [21]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
slice_arr[:] = 99 # broadcast changes the underlying array
# Data is not copied, it's a view of the original array! This avoids memory problems!

In [23]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
# To get a copy of an array, need to be explicit
arr2 = arr.copy()

In [27]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr2[:] = 100

In [29]:
arr2

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [31]:
arr # broadcasting of copied array doesn't change original array  

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [33]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]]) # 3x3 array

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[0][0]

5

In [36]:
arr_2d[0,0]

5

In [38]:
arr_2d[2][2]

45

In [39]:
arr_2d[2,2]

45

In [40]:
# entire row
arr_2d[2]

array([35, 40, 45])

In [47]:
arr_2d[2,:]

array([35, 40, 45])

In [49]:
# 2D array slicing
arr_2d[:2,1:] # rows 0 and 1, cols 1 and 2

array([[10, 15],
       [25, 30]])

In [52]:
arr_2d[:2] # rows 0 and 1

array([[ 5, 10, 15],
       [20, 25, 30]])

In [55]:
# entire column
arr_2d[:,:1] #as matrix

array([[ 5],
       [20],
       [35]])

In [56]:
# entire column
arr_2d[:,1] #as array

array([10, 25, 40])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [59]:
arr2d = np.zeros((10,10))

In [60]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
arr_len = arr2d.shape[1]

In [67]:
arr_len

10

In [68]:
for i in range(arr_len):
    arr2d[i] = i

In [69]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [70]:
arr2d[[2,4,6,8]] # multiple rows

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [72]:
arr2d[[2,4,6,8],:5] # multiple rows, first 5 cols

array([[2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8.]])

In [76]:
#Allows in any order
arr2d[[7,4,9,3,8]]

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [77]:
arr = np.arange(1,11)

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr > 5 # returns array of booleans

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
bool_arr = arr > 5

In [82]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [84]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [83]:
# conditional selection
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [85]:
x = 4
arr[arr>x]

array([ 5,  6,  7,  8,  9, 10])

In [89]:
arr_2d = np.arange(50).reshape(5,10) # 5 rows, 10 cols

In [90]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [93]:
# grab [[13,14],[23,24]] in row 1 to 2, col 3 to 4
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [97]:
arr_2d[1:,5:9]

array([[15, 16, 17, 18],
       [25, 26, 27, 28],
       [35, 36, 37, 38],
       [45, 46, 47, 48]])